apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # echo -n 'root' | base64
  mongo-root-username: cm9vdA==
  # echo -n 'Chris' | base64
  mongo-root-password: Q2hyaXMK